run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - misspell
    - gocyclo
    - goimports
    - revive
    - stylecheck

linters-settings:
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US
  goimports:
    local-prefixes: github.com/alauda/nexus-cli

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
